### ISSUE TITLE
Is "is:issue is:open" supposed to be here?

### ISSUE THREAD

**Issue by adereth-mids** [MIDS-scaling-up/v2#4]
https://github.com/MIDS-scaling-up/v2/blob/9b96fac3457b708a57bde97f71713fd0dd7267cf/week01/lab/Dockerfile.yolo#L19

It seems to be a typo and breaks docker. It works when I remove this line.

**Comment by rbraddes** [comment]
I updated the Dockerfile.

Thanks!
