### ISSUE TITLE
Recent Changes to HW6 download.sh script breaks repo

### ISSUE THREAD

**Issue by sirakzg** [MIDS-scaling-up/v2#42]
Specifically  commit:
https://github.com/MIDS-scaling-up/v2/commit/dff675c5b5facef33b20e287e34cdad059e261e5#diff-37a0f51b49e944d6095aab23fd89f5ed

Commenting out lines for data + bert_config.json files.

**Comment by darraghdog** [comment]
Thanks, hw6 updated and this script is removed.
